paluf_team:
    resource: "@PalufTeamBundle/Controller/"
    type:     annotation
    prefix:   /team

paluf_admin:
    resource: "@PalufAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

paluf:
    resource: "@PalufBundle/Controller/"
    type:     annotation
    prefix:   /
